FROM mineru:2.5-vllm-cu124

#
# offline swagger/redoc
#

COPY mineru_offline_docs.py \
    /usr/local/lib/python3.12/dist-packages/mineru_offline_docs.py

COPY patch_fastapi.py \
    /tmp/patch_fastapi.py

COPY static/ \
    /opt/mineru-static/

RUN python3 /tmp/patch_fastapi.py && \
    rm -f /tmp/patch_fastapi.py

