services:
  mineru-api:
    #image: mineru:2.5-vllm  # 使用了在线js和css资源的 swagger-ui 镜像，相关资源需要联网下载，否则swagger-ui不能正常显示
    image: mineru:2.5-vllm-offline # 可以离线使用的 swagger-ui 镜像，内置了 vLLM 相关依赖
    container_name: mineru-vllm
    restart: always
    # profiles: ["api"]  # 注释掉此行，否则直接运行 docker compose up -d 将不会启动该服务
    ports:
      - "8000:8000"  # 推荐加上引号，避免 YAML 解析端口时出现偶发错误
    environment:
      MINERU_MODEL_SOURCE: local
      VLLM_ENABLE_CUDA_COMPATIBILITY: "1"  # 默认是cuda13.0，设置为 1 向下兼容到 cuda12.4
      HF_HUB_OFFLINE: "1"
      HF_HUB_DISABLE_TELEMETRY: "1"
      VLLM_NO_USAGE_STATS: "1"
      MODELSCOPE_ENVIRONMENT: "offline"
      DO_NOT_TRACK: "1"
    entrypoint: mineru-api  # 如果你需要完整兼容 OpenAI 格式，此处也可改为上一轮聊到的 mineru-openai-server
    command: >
      --host 0.0.0.0
      --port 8000
      # --allow-public-http-client
      --gpu-memory-utilization 0.8
      --max-num-seqs 4
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 6G
          devices:
            - driver: nvidia
              device_ids: ["0"]  # A10 显卡所在的 ID
              capabilities: [gpu]
